language: cpp

script: cmake

compiler:
  - clang
  - gcc
  
env:
  global:
    - GCC_VERSION="4.8"

before_install:
  - echo $LANG
  - echo $LC_ALL
  - export SOURCE_ROOT=`pwd`;
  - npm install
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  # gcc before_install
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq -y --force-yes g++-${GCC_VERSION}; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  
  # clang before_install
  - if [ "$CXX" == "clang++" ]; then export LIBCXX=On; fi
  - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && $cwd; fi
  # clang libcxxabi for gtest
  - if [ "$CXX" == "clang++" ]; then cd ${SOURCE_ROOT}; fi
  - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi; fi
  - if [ "$CXX" == "clang++" ]; then cd libcxxabi/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++abi.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++abi.so.1.0 libc++abi.so.1 && $cwd; fi
  
  # GLFW before_install
  - sudo apt-get install -qq -y libXxf86vm-dev

branches:
  only:
  - master

script:
  - cd ${SOURCE_ROOT}
  - grunt build
  - cd build
  - make

notifications:
  email: false
