language: cpp

sudo: false

compiler:
#- clang
- gcc

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.5
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    packages:
    #- clang-3.5
    - cmake
    - g++-4.9
    # Coveralls
    - curl
    # GLFW
    - libxxf86vm-dev
cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - GCC_VERSION="4.9"

before_install:
  - echo $LANG
  - echo $LC_ALL
  - export SOURCE_ROOT=`pwd`;
  - npm install
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}" GCOV="gcov-${GCC_VERSION}"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi

branches:
  only:
  - master

script:
  # build
  - cd ${SOURCE_ROOT}
  - grunt build
  - cd build
  - make
  # coveralls build
  - cd ${SOURCE_ROOT}
  - grunt build:coveralls
  - cd cbuild
  - make
  - make coveralls

before_cache:
  - ccache --show-stats

notifications:
  email: false
