language: cpp

compiler:
  - clang
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
  - npm install
  # GLFW dependencies
  - sudo apt-get install libXxf86vm-dev

branches:
  only:
  - master

script:
  - grunt build
  - cd build
  - make